In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [6]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [7]:
a[0]

array([1, 2, 3, 4])

In [8]:
a = np. array([1, 2, 3])

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.ones(2)

array([1., 1.])

In [11]:
np.empty(2)

array([1., 1.])

In [12]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [13]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
x = np.ones(2, dtype=np.int64)

In [15]:
x

array([1, 1])

In [16]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [17]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [19]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [21]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
array_example = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])

In [23]:
array_example.ndim


3

In [24]:
array_example.size

24

In [25]:
array_example.shape

(3, 2, 4)

In [26]:
a = np.arange(6)

In [27]:
a

array([0, 1, 2, 3, 4, 5])

In [28]:
b = a.reshape(3, 2)

In [29]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [30]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [31]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [32]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [33]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [34]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [35]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [36]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [37]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [38]:
data = np.array([1, 2, 3])
data[1]

2

In [39]:
data[0:2]

array([1, 2])

In [40]:
data[1:]

array([2, 3])

In [41]:
data[-2:]

array([2, 3])

In [42]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [43]:
a[a < 5]

array([1, 2, 3, 4])

In [45]:
five_up = (a >= 5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
divisible_by_2 = a[a%2==0]

In [47]:
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [48]:
c = a[(a > 2) & (a < 11)]

In [49]:
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
five_up = (a > 5) | (a == 5)

In [51]:
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [52]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [53]:
b = np.nonzero(a < 5)

In [54]:
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [56]:
list_of_coordinates= list(zip(b[0], b[1]))

In [61]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [62]:
a[b]

array([1, 2, 3, 4])

In [63]:
not_there = np.nonzero(a == 42)

In [64]:
not_there

(array([], dtype=int64), array([], dtype=int64))

In [65]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [67]:
a1 = np.array([[1, 1], [2, 2]])

In [68]:
a2 = np.array([[3, 3], [4, 4]])

In [71]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [72]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [73]:
x = np.arange(1, 25).reshape(2, 12)

In [74]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [75]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [76]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [77]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [78]:
b1 = a[0, :]

In [79]:
b1

array([1, 2, 3, 4])

In [80]:
b1[0] = 99

In [81]:
b1

array([99,  2,  3,  4])

In [82]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
b2 = a.copy()

In [84]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [85]:
data - ones

array([0, 1])

In [86]:
data * data

array([1, 4])

In [87]:
data / data

array([1., 1.])

In [88]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [89]:
b = np.array([[1, 1], [2, 2]])

In [90]:
b.sum(axis=0)

array([3, 3])

In [91]:
b.sum(axis=1)

array([2, 4])

In [92]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [94]:
data.max()

2.0

In [95]:
data.min()

1.0

In [96]:
data.sum()

3.0

In [97]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [98]:
a.sum()

4.8595784

In [99]:
a.min()

0.05093587

In [100]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [101]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
data[0, 1]

2

In [103]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [104]:
data[0:2, 0]

array([1, 3])

In [105]:
data.max()

6

In [106]:
data.min()

1

In [107]:
data.sum()

21

In [108]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [109]:
data.max(axis=0)

array([5, 6])

In [110]:
data.max(axis=1)

array([2, 5, 6])

In [111]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [112]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [113]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [114]:
np.ones(3)

array([1., 1., 1.])

In [115]:
np.zeros(3)


array([0., 0., 0.])

In [116]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

array([0.39780677, 0.51614547, 0.13574137])

In [117]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [118]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [119]:
rng.random((3, 2)) 


array([[0.35408099, 0.20977375],
       [0.2186937 , 0.58410012],
       [0.80628826, 0.8711161 ]])

In [120]:
rng.integers(5, size=(2, 4)) 

array([[0, 1, 2, 1],
       [0, 0, 2, 3]])

In [121]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [122]:
unique_values = np.unique(a)

In [123]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [125]:
unique_values, indices_list = np.unique(a, return_index=True)

In [126]:
indices_list

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14])

In [127]:
unique_values, occurrence_count = np.unique(a, return_counts=True)

In [128]:
occurrence_count

array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1])

In [129]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [130]:
unique_values = np.unique(a_2d)

In [131]:
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [132]:
unique_rows = np.unique(a_2d, axis=0)

In [133]:
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [134]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)

In [135]:
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [136]:
indices

array([0, 1, 2])

In [137]:
occurrence_count

array([2, 1, 1])

In [138]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [140]:
arr = np.arange(6).reshape((2, 3))

In [141]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [142]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [143]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [144]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [145]:
reversed_arr = np.flip(arr)

In [146]:
'Reversed Array: ', reversed_arr

('Reversed Array: ', array([8, 7, 6, 5, 4, 3, 2, 1]))

In [147]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [148]:
reversed_arr = np.flip(arr_2d)

In [149]:
reversed_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [150]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

In [151]:
reversed_arr_rows

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [152]:
reversed_arr_columns = np.flip(arr_2d, axis=1)

In [153]:
reversed_arr_columns

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [154]:
arr_2d[1] = np.flip(arr_2d[1])

In [155]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [156]:
arr_2d[:,1] = np.flip(arr_2d[:,1])

In [157]:
arr_2d

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])

In [158]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [159]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [160]:
a1 = x.flatten()

In [161]:
a1[0] = 99

In [162]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [163]:
a1

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [164]:
a2 = x.ravel()

In [165]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [166]:
a2[0] = 98

In [167]:
x

array([[98,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])